server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoint:
    gateway:
      enabled: true # default value
    web:
      exposure:
        include: gateway
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: quote-service
          uri: lb://quote-service
          predicates:
          - Path=/foo/**
          filters:
          - RewritePath=/foo/(?<segment>.*), /quote/$\{segment}

mapping:
  quote:
    base: /quote
    alias1: /quote/{id}
